apiVersion: v1
kind: Pod
metadata:
  name: pv-dynamic
  labels:
    run: mysql
spec:
  containers:
    - name: mysql 
      image: mysql:8
      ports:
        - containerPort: 3306
      volumeMounts:
        - name: aws-pv
          mountPath: /var/lib/mysql
  volumes:
    - name: aws-pv
      persistentVolumeClaim: 
        claimName: mysql-pvc
  
      