---
apiVersion: batch/v1
kind: Job
metadata:
  name: tempjob
spec:
  template:
    metadata:
      name: hellopod
    spec:
      containers:
        - name: hello
          image: alpine
          command: 
            - sleep
            - 10s