---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: CronJob
  labels:
    app: lebel-nginix
spec:
  schedule: 1 * * * *
  jobTemplate:
    metadata:
      name: CronJob
      labels:
        app: label-nginix
    spec:
      selector:
        matchLabels:
          app: label-nginix
      template:
        metadata:
          labels:
            app: label-nginix
          name: CronJob
        spec:
          containers:
            - name: spc
              image: redis:7.2 
              args:
                - sleep
              command:
                - 10s

  