---
apiVersion: v1
kind: Pod
metadata:
  name: nginx
spec:
  containers:
    - name: nginx
      image: nginx:1.24.0-perl
      ports:
        - containerPort: 80
    - name: alpine
      image: alpine:3.17
      args:
        - sleep
        - 1d
