---
apiVersion: v1
kind: pod
metadata:
  name: restartpolicy
spec:
  - restartpolicy: never
    name: alpine
    image: alpine:1.23
    containerPort:
      - name: alpine
        port: 80
---        
apiVersion: v1 
kind: pod
metadata: 
  name: restartpolicy
spec: 
  - restartpolicy: success
    name: httpd
    image: httpd:1:3
    containerPort:
      - name: httpd
        port: 80
---
apiVersion: batch/v1
kind: job
metadata: 
  name: spring-pet-clinic
spec: 
  - name: spc
    manualSelector: failure
    selector: 
      - labelselector:  
        key: merge
        operator: Exists
        values: empty

  

