apiVersion:	v1
kind: Pod
metadata:
  name: onfailure
spec:
  restartPolicy: OnFailure
  containers:
    - name: gameoflife
      image: batchusivaji/kishore:1.1
      args:
        - sleep
        - 10mb
---
apiVersion:	v1
kind: Pod
metadata:
  name: onfailure
spec:
  restartPolicy: OnFailure
  containers:
    - name: gameoflife
      image: batchusivaji/kishore:1.1
      ports:
        - containerPort: 9090

---
apiVersion: v1
kind: Pod
metedata: 
  name: on-failure
  labels: 
    app: web
spec:
  activeDeadlineSeconds: 2
  
  restartPolicy: OnFailure
  containers:
    - name: httpd
      image: httpd
      ports: 
        - containerPort: 80
    - name: alpine
      image: alpine
      args:
        - sleep
        - 10CC

      