---
apiVersion: v1
kind: ReplicationController
metadata:
  name: replication
  labels:
    app: redis
spec:
  minReadySeconds: 5
  replicas: 5
  selector:
    app: redis                
  template:
    metadata:
      labels:
        app: redis
    spec:
      activeDeadlineSeconds: 2
      containers:
        - name: redis
        - image: redis:7.2
          args:
            - sleep
          command:
            - 15s