---
apiVersion: v1
kind: ReplicationController
metadata:
  name: replication
  labels:
    app: redis
    version: 7.2
spec:
  minReadySeconds: 5
  replicas: 5
  selector:
    app: replication
  template:
    name: app
    metadata:
      labels:
        app: redis
    spec:
      
      containers:
        - name: replication
        - image: redis:7.2
          args:
            - sleep
          command:
            - 15s