---
apiVersion: v1
kind: ReplicationController
metadata:
  name: replication-controller
  labels:
    app: redis
spec:
  minReadySeconds: 2
  replicas: 2
  selector:
    app: redis                
  template:
    metadata:
      labels:
        app: redis:7.2
    spec:
      activeDeadlineSeconds: 2
      containers:
        - name: redis
        - image: redis
          args:
            - sleep
            - 1s