---
apiVersion: v1
kind: Service
metadata:
  name: httpd
  labels:
    run: test
spec:
  selector:
    app: dev
  ports:
    - port: 80
      protocol: TCP
      targetPort: 32000
  type: LoadBalancer