---
apiVersion: v1
kind: Service
metadata:
  name: httpd
  labels:
    run: dev
spec:
  selector:
    app: test
  ports:
    - port: 80
      protocol: TCP
      targetPort: 32000
  type: LoadBalancer