apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata: 
  name: test
  namespace: dev
rules:
  - apiGroups: ["rbac.authorization.k8s.io/v1"]
    resources: [ "pods" ]
    verbs: ["get", "list","delete"] 
      