apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: qat
  namespace: dev
roleRef:
  apiGroup: ["*"]
  kind: user
  name: qat
subjects:
  - apiGroup: ["*"]
    kind: role
    name: myaccount
