apiVersion: rbac.authorization.k8s.io/v1
# This role binding allows "test" to read pods in the namespace in dev
kind: RoleBinding
metadata:
  name: test
  namespace: dev
roleRef: # "roleRef" specifies the binding to a Role
  apiGroup: "" #indicates the core API group
  kind: Role  # this must be Role
  name: reader   # this must match the name of the Role or ClusterRole you wish to bind to
subjects: # You can specify more than one "subject"
  - apiGroup: ""
    kind: User
    name: qat
