---
apiVersion: v1	
kind: Service
metadata:
  name: httpd-service
  labels:
    run: httpd
spec:
  ports:
    - name: httpd
      port: 80
      protocol: TCP
      targetPort: 32000
  selector:
    run: httpd
  type: LoadBalancer


---

apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: httpd
  labels:
    run: dev
spec:
  minReadySeconds: 3
  replicas: 2
  selector:
    matchExpressions:
      - key: httpd
        operator: NotIn
        values:
          - dev
          - test

      - key: nginx
        operator: In
        values:
          - qualityThought
          - ihub
  template:
    metadata:
      name: dev
      labels:
        httpd: qt
        nginx: ihub
    spec:
      containers:
        - name: httpd-service
          image: httpd:2.4.57
          ports: 
            - containerPort: 80
              protocol: TCP
          readinessProbe:
            failureThreshold: 2
            initialDelaySeconds: 2
            periodSeconds: 10
            successThreshold: 3
            httpGet:
              path: /
              port: 80
          livenessProbe:
            failureThreshold: 3
            initialDelaySeconds: 1
            periodSeconds: 15
            successThreshold: 1
            httpGet:
              path: /
              port: 80