---
apiVersion:	v1
kind: Pod
metadata:
  name: onfailure
spec:
  restartPolicy: OnFailure
  containers:
    - name: failure
      image: nginix
      args:
        - sleep
        - 10mb
---
apiVersion: v1
kind: Pod
metadata:
  name: onfailure1
spec:
  restartPolicy: OnFailure
  containers:
    - name: success
      image: nginix
      args:
        - sleep
        - 1s




      